% nCfield
% line720

close all
fmecaengine(... without auto expansion
    'local','D:\Data\Olivier\INRA\Etudiants & visiteurs\Audrey Goujon\illustration_fmeca\',...
    'fmecamainfile','debugOV.ods',...
    'inputpath','inputs', ...
    'outputpath','debug' ...
    );